CREATE TABLE project (
  id VARCHAR(36) PRIMARY KEY, name VARCHAR(160) NOT NULL,
  description TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE research_task (
  id VARCHAR(36) PRIMARY KEY, project_id VARCHAR(36) NOT NULL REFERENCES project(id),
  title VARCHAR(240) NOT NULL, objective TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX task_project_idx ON research_task(project_id);
CREATE TABLE workflow_run (
  id VARCHAR(36) PRIMARY KEY, task_id VARCHAR(36) NOT NULL REFERENCES research_task(id),
  project_id VARCHAR(36) NOT NULL REFERENCES project(id), task_title VARCHAR(240) NOT NULL,
  objective TEXT NOT NULL, workflow_version VARCHAR(40) NOT NULL,
  status VARCHAR(32) NOT NULL, execution_mode VARCHAR(16) NOT NULL,
  idempotency_key VARCHAR(128), created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT run_idempotency_uq UNIQUE(task_id,idempotency_key)
);
CREATE INDEX run_status_idx ON workflow_run(status);
CREATE TABLE node_run (
  id VARCHAR(36) PRIMARY KEY, run_id VARCHAR(36) NOT NULL REFERENCES workflow_run(id),
  node_key VARCHAR(32) NOT NULL, label VARCHAR(100) NOT NULL, position INTEGER NOT NULL,
  status VARCHAR(32) NOT NULL, started_at TIMESTAMP WITH TIME ZONE,
  finished_at TIMESTAMP WITH TIME ZONE, detail TEXT NOT NULL,
  CONSTRAINT node_position_uq UNIQUE(run_id,position)
);
CREATE TABLE run_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id VARCHAR(36) NOT NULL REFERENCES workflow_run(id),
  event_type VARCHAR(64) NOT NULL, message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX event_run_idx ON run_event(run_id,id);
CREATE TABLE approval_request (
  id VARCHAR(36) PRIMARY KEY, run_id VARCHAR(36) NOT NULL UNIQUE REFERENCES workflow_run(id),
  status VARCHAR(32) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  decision VARCHAR(16), comment TEXT NOT NULL, decided_at TIMESTAMP WITH TIME ZONE
);
CREATE TABLE artifact (
  id VARCHAR(36) PRIMARY KEY, run_id VARCHAR(36) NOT NULL REFERENCES workflow_run(id),
  name VARCHAR(240) NOT NULL, media_type VARCHAR(100) NOT NULL,
  sha256 VARCHAR(64) NOT NULL, size_bytes BIGINT NOT NULL,
  relative_path VARCHAR(512) NOT NULL UNIQUE, created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT artifact_name_uq UNIQUE(run_id,name)
);
CREATE TABLE audit_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR(64) NOT NULL, entity_id VARCHAR(36) NOT NULL,
  actor VARCHAR(40) NOT NULL, detail TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
