CREATE TABLE assistant_session (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  status VARCHAR(16) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE assistant_message (
  id VARCHAR(36) PRIMARY KEY,
  message_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  session_id VARCHAR(36) NOT NULL REFERENCES assistant_session(id),
  turn_id VARCHAR(36) NOT NULL,
  role VARCHAR(16) NOT NULL,
  content TEXT NOT NULL,
  status VARCHAR(16) NOT NULL,
  context_title VARCHAR(240) NOT NULL,
  context_summary TEXT NOT NULL,
  context_content TEXT NOT NULL,
  prompt_content TEXT NOT NULL,
  idempotency_key VARCHAR(128),
  request_hash VARCHAR(64),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT assistant_turn_role_uq UNIQUE(turn_id,role),
  CONSTRAINT assistant_idempotency_uq UNIQUE(session_id,idempotency_key)
);
CREATE INDEX assistant_message_session_idx ON assistant_message(session_id,message_order);
CREATE INDEX assistant_message_status_idx ON assistant_message(status,role);
CREATE TABLE assistant_runtime_lock (
  id INTEGER PRIMARY KEY
);
INSERT INTO assistant_runtime_lock(id) VALUES (1);
